application:
  db:
    url: "user=kumparan password=password host=localhost port=5444 dbname=kumparan sslmode=disable"
  port: 8000

elastic:
  host: "http://localhost:9200"

amqp:
  uri: "amqp://guest:guest@localhost:5672/"
